baseurl = "https://www.stefanoguerrini.dev"
theme = "hugo-coder"
languagecode = "en"
defaultcontentlanguage = "en"
title = "Stefano Guerrini - Developer"
googleAnalytics = "UA-120827713-1"


[params]
    author = "Stefano Guerrini"
    info = "Backend Developer"

    description = "Personal page of a common developer."
    keywords = "java,backend,stefano guerrini,milan,developer,coding"

    dateformat = "2 Jan 2006"
    favicon_32 = "/img/favicon-32x32.png"
    favicon_16 = "/img/favicon-16x16.png"


    #footercontent = "Enter a text here."
    hidecredits = true
    hidecopyright = true
    rtl = false
    math = true
    custom_css = ["css/custom.css"]

# Social links
[[params.social]]
    name = "Github"
    icon = "fab fa-github fa-2x"
    weight = 1
    url = "https://github.com/StefanoGuerrini"
[[params.social]]
    name = "LinkedIn"
    icon = "fab fa-linkedin fa-2x"
    weight = 4
    url = "https://www.linkedin.com/in/stefanoguerrini"
[[params.social]]
    name = "Twitter"
    icon = "fab fa-twitter fa-2x"
    weight = 3
    url = "https://twitter.com/GuerriniStefano"
[[params.social]]
    name = "Stackoverflow"
    icon = "fab fa-stack-overflow fa-2x"
    weight = 5
    url = "https://stackoverflow.com/users/5002696"
[[params.social]]
    name = "Contact"
    icon = "far fa-envelope fa-2x"
    weight = 5
    url = "mailto:sayhey@stefanoguerrini.dev"


[[menu.main]]
    name = "About"
    weight = 2
    url = "/about/"

[[menu.main]]
    #name = "Blog"
    weight = 2
    url = "/posts/"